# Generated by Django 6.0 on 2025-12-19 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
